baseurl: "https://mverwaerde.github.io/naissance/"
title: "Liste de naissance"

permalinks:
  pages: /:slug

params:
  # Style options: pink, blue, green, red, sea, violet, gold
  # Use custom.css for your custom styling
  style: "gold"

  # Contact form uses www.formspree.io
  endpoint: "xnqlwaal"

  # Personal International Bank Account Number
  identity: "M. JARDIN FLORENT MARINE"
  iban: "FR76 3007 6029 5830 9744 0030 075"

  # Nav links in the side bar
  navlinks:
  - name: "Notre démarche"
    url: "demarche/"

  - name: "Nous contacter"
    url: "contacter/"

  social:
    github: "https://github.com/mverwaerde/naissance/"
